Document: lightverifier
Title: Debian lightverifier Manual
Author: <insert document author here>
Abstract: This manual describes what lightverifier is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lightverifier/lightverifier.sgml.gz

Format: postscript
Files: /usr/share/doc/lightverifier/lightverifier.ps.gz

Format: text
Files: /usr/share/doc/lightverifier/lightverifier.text.gz

Format: HTML
Index: /usr/share/doc/lightverifier/html/index.html
Files: /usr/share/doc/lightverifier/html/*.html
